// Fake sentiment profiles — demo data until the /hr/sentiment ML pipeline ships.
import { CandidateSentimentProfile } from '@/types';

export const FAKE_SENTIMENT_PROFILES: CandidateSentimentProfile[] = [
  {
    id: 'fake-001',
    candidateName: 'candidate.alex',
    role: 'Senior Frontend Engineer',
    avatar: 'https://i.pravatar.cc/96?img=12',
    interviewDate: '2026-08-05',
    durationMinutes: 42,
    overallStressScore: 34,
    confidenceRating: 82,
    speechClarityScore: 88,
    avgPauseDurationSec: 1.2,
    biomarkers: {
      audioTone: { steadyPercent: 86, tremorPercent: 6, status: 'Steady & Calm' },
      speechPace: { wpm: 146, idealRange: '135-160 WPM', status: 'Optimal (145 WPM)' },
      pitchVariation: { hzStdDev: 9, status: 'Dynamic & Natural' },
      pausePatterns: { pausesPerMin: 4, longPauseCount: 0, status: 'Natural Cadence' },
    },
    journeyGraph: [
      { time: '0:00', minute: 0, topic: 'Intro & Background', confidence: 78, stress: 28, hesitation: 12, emotionLabel: 'Neutral' },
      { time: '2:40', minute: 2, topic: 'React Internals', confidence: 84, stress: 22, hesitation: 8, emotionLabel: 'Confident' },
      { time: '6:10', minute: 6, topic: 'Performance Profiling', confidence: 88, stress: 18, hesitation: 5, emotionLabel: 'Enthusiastic' },
      { time: '9:30', minute: 9, topic: 'Live Coding Task', confidence: 74, stress: 52, hesitation: 30, emotionLabel: 'Hesitant' },
      { time: '12:50', minute: 12, topic: 'Debugging Memory Leak', confidence: 80, stress: 38, hesitation: 15, emotionLabel: 'Confident' },
      { time: '16:20', minute: 16, topic: 'System Design', confidence: 86, stress: 30, hesitation: 10, emotionLabel: 'Enthusiastic' },
    ],
    transcriptWithSentiment: [
      {
        id: 1,
        timestamp: '00:12',
        topic: 'Intro & Background',
        speaker: 'AI Agent',
        text: 'Welcome! Could you start by introducing yourself and your experience with modern React?',
        emotion: 'Neutral',
        audioMetrics: { pitch: '180 Hz', pace: '142 WPM', tone: 'Calm' },
      },
      {
        id: 2,
        timestamp: '00:48',
        topic: 'Intro & Background',
        speaker: 'Candidate',
        text: 'Sure — I have five years building large-scale React apps, most recently leading the design-system team at a fintech startup.',
        emotion: 'Confident',
        audioMetrics: { pitch: '190 Hz', pace: '148 WPM', tone: 'Steady' },
        hrInsight: {
          type: 'High Mastery',
          title: 'Clear narrative arc',
          explanation: 'Candidate introduced seniority and leadership scope early; steady vocal tone indicates low nerves.',
        },
      },
      {
        id: 3,
        timestamp: '04:05',
        topic: 'Live Coding Task',
        speaker: 'AI Agent',
        text: 'Let’s move to a coding exercise. Implement a memoized selectors factory for a large derived state tree.',
        emotion: 'Neutral',
        audioMetrics: { pitch: '175 Hz', pace: '138 WPM', tone: 'Calm' },
      },
      {
        id: 4,
        timestamp: '04:40',
        topic: 'Live Coding Task',
        speaker: 'Candidate',
        text: 'Okay, I’ll start with the cache keyed by dependency hash... let me think about the invalidation strategy here.',
        emotion: 'Hesitant',
        audioMetrics: { pitch: '210 Hz', pace: '152 WPM', tone: 'Pitched Up' },
        hrInsight: {
          type: 'Nervousness',
          title: 'Stress spike on new problem',
          explanation: 'Pitch rose ~30 Hz and speech accelerated at task onset — but recovered within 90s once the approach was decided.',
        },
      },
      {
        id: 5,
        timestamp: '08:15',
        topic: 'Debugging Memory Leak',
        speaker: 'Candidate',
        text: 'The leak is likely from an unmounted effect that never cleared its subscription — I’d add a cleanup and verify with the profiler.',
        emotion: 'Confident',
        audioMetrics: { pitch: '185 Hz', pace: '144 WPM', tone: 'Steady' },
      },
    ],
  },
  {
    id: 'fake-002',
    candidateName: 'jordan.smith',
    role: 'Backend Engineer',
    avatar: 'https://i.pravatar.cc/96?img=68',
    interviewDate: '2026-08-06',
    durationMinutes: 38,
    overallStressScore: 61,
    confidenceRating: 58,
    speechClarityScore: 72,
    avgPauseDurationSec: 2.4,
    biomarkers: {
      audioTone: { steadyPercent: 62, tremorPercent: 18, status: 'Mild Anxiety' },
      speechPace: { wpm: 178, idealRange: '135-160 WPM', status: 'Rushed (185 WPM)' },
      pitchVariation: { hzStdDev: 14, status: 'High Pitch Spikes' },
      pausePatterns: { pausesPerMin: 7, longPauseCount: 3, status: 'Frequent Pauses' },
    },
    journeyGraph: [
      { time: '0:00', minute: 0, topic: 'Intro & Background', confidence: 62, stress: 44, hesitation: 18, emotionLabel: 'Neutral' },
      { time: '3:20', minute: 3, topic: 'Distributed Systems', confidence: 66, stress: 48, hesitation: 20, emotionLabel: 'Hesitant' },
      { time: '7:00', minute: 7, topic: 'Database Indexing', confidence: 58, stress: 60, hesitation: 34, emotionLabel: 'Stressed' },
      { time: '10:40', minute: 10, topic: 'Rate Limiting Design', confidence: 50, stress: 72, hesitation: 40, emotionLabel: 'Stressed' },
      { time: '14:10', minute: 14, topic: 'System Design Walkthrough', confidence: 54, stress: 66, hesitation: 30, emotionLabel: 'Hesitant' },
    ],
    transcriptWithSentiment: [
      {
        id: 1,
        timestamp: '00:30',
        topic: 'Intro & Background',
        speaker: 'AI Agent',
        text: 'Thanks for joining. Walk me through the most complex distributed system you’ve built.',
        emotion: 'Neutral',
        audioMetrics: { pitch: '170 Hz', pace: '140 WPM', tone: 'Calm' },
      },
      {
        id: 2,
        timestamp: '01:05',
        topic: 'Distributed Systems',
        speaker: 'Candidate',
        text: 'We ran a multi-region event pipeline with... uh, Kafka and... let me recall the exact consumer group setup.',
        emotion: 'Hesitant',
        audioMetrics: { pitch: '205 Hz', pace: '172 WPM', tone: 'Pitched Up' },
        hrInsight: {
          type: 'Nervousness',
          title: 'Mid-recall stall',
          explanation: 'Three stalls over 2s suggest the candidate was recalling details rather than fabricating — verify depth with targeted follow-up.',
        },
      },
      {
        id: 3,
        timestamp: '05:40',
        topic: 'Rate Limiting Design',
        speaker: 'AI Agent',
        text: 'Design a rate limiter for a public API handling 50k RPS per tenant.',
        emotion: 'Neutral',
        audioMetrics: { pitch: '172 Hz', pace: '139 WPM', tone: 'Calm' },
      },
      {
        id: 4,
        timestamp: '06:20',
        topic: 'Rate Limiting Design',
        speaker: 'Candidate',
        text: 'I’d go with a token bucket per tenant, stored in Redis with a sliding window counter...',
        emotion: 'Stressed',
        audioMetrics: { pitch: '220 Hz', pace: '186 WPM', tone: 'High Pitch' },
        hrInsight: {
          type: 'Skill Gap',
          title: 'Solid idea, shaky delivery',
          explanation: 'Correct token-bucket answer, but delivery was rushed and one long pause before “sliding window” — likely knowledge gap on window algorithms.',
        },
      },
    ],
  },
];
