'use client';

import { useState, useEffect, useRef } from 'react';
import { getTopicsForRoleAndCompany } from '@/lib/interviewTopics';
import { evaluateInterview } from '@/lib/interviewScorer';
import { apiClient } from '@/lib/apiClient';
import { siteConfig } from '@/lib/config';

export interface Message {
  id: string;
  role: 'ai' | 'candidate';
  content: string;
  timestamp: string;
}

export type InterviewPhase = 'Introduction' | 'Core Vetting' | 'Deep-Dive' | 'Wrap-up';

interface UseInterviewSessionProps {
  company: string;
  role: string;
  difficulty?: string;
  storageKey: string;
  interviewId?: string;
  onComplete: (data: unknown) => void;
}

export function useInterviewSession({
  company,
  role,
  storageKey,
  interviewId,
  onComplete,
}: UseInterviewSessionProps) {
  const [stage, setStage] = useState<'check' | 'session' | 'fallback'>('check');
  const [phase, setPhase] = useState<InterviewPhase>('Introduction');
  const [messages, setMessages] = useState<Message[]>([]);
  const [timeRemaining, setTimeRemaining] = useState(900); // 15 mins
  const [micActive, setMicActive] = useState(true);
  const [camActive, setCamActive] = useState(true);
  const [isAnalyzing, setIsAnalyzing] = useState(false);
  const [aiRespondError, setAiRespondError] = useState<string | null>(null);
  const [proctorTelemetry, setProctorTelemetry] = useState({
    faceCount: null as number | null,
    gazeCentered: null as boolean | null,
    engagementIndex: null as number | null,
  });
  const [strikeCount, setStrikeCount] = useState(0);
  const [showWarningModal, setShowWarningModal] = useState(false);

  const topicIndex = useRef(0);
  const isFollowUp = useRef(false);
  const transcriptData = useRef<{ question: string; answer: string; feedback: string }[]>([]);
  const messagesRef = useRef<Message[]>([]);
  // Template questions (source: 'template') used for the opening message and as
  // an offline fallback. Live questions are generated by the interviewer agent
  // and come back in the /api/v1/ai/interview/respond response when reachable.
  const topics = getTopicsForRoleAndCompany(role, company);

  // Keep a ref mirror of messages so async callbacks (submitAnswer's timeouts,
  // handleComplete) read the latest transcript, not a stale render closure.
  useEffect(() => {
    messagesRef.current = messages;
  }, [messages]);

  useEffect(() => {
    if (stage !== 'session' && stage !== 'fallback') return;
    if (showWarningModal) return;
    const t = setInterval(() => {
      setTimeRemaining((prev) => (prev > 0 ? prev - 1 : 0));
    }, 1000);
    return () => clearInterval(t);
  }, [stage, showWarningModal]);

  // Periodic proctoring telemetry logging to Express API (only real CV signals, never fabricated)
  useEffect(() => {
    if (stage !== 'session' || !interviewId) return;
    const pTimer = setInterval(async () => {
      try {
        await apiClient.patch(`/interviews/${interviewId}/proctoring`, {
          face_count: null,
          gaze_centered: null,
          engagement_index: null,
          multiple_faces_detected: null,
        });
      } catch {
        // Silently swallow background telemetry errors
      }
    }, 8000);
    return () => clearInterval(pTimer);
  }, [stage, interviewId]);

  // Anti-Cheat proctoring listeners for fullscreen and visibility changes
  useEffect(() => {
    if (stage !== 'session') return;

    const handleProctoringViolation = () => {
      if (document.hidden || !document.fullscreenElement) {
        setStrikeCount((prev) => {
          const next = prev + 1;
          setShowWarningModal(true);
          return next;
        });
      }
    };

    document.addEventListener('fullscreenchange', handleProctoringViolation);
    document.addEventListener('visibilitychange', handleProctoringViolation);

    return () => {
      document.removeEventListener('fullscreenchange', handleProctoringViolation);
      document.removeEventListener('visibilitychange', handleProctoringViolation);
    };
  }, [stage]);

  const startSession = async () => {
    setStage('session');
    setPhase('Introduction');
    setIsAnalyzing(true);

    if (document.documentElement.requestFullscreen) {
      document.documentElement.requestFullscreen().catch((err) => {
        console.error('Failed to enter fullscreen:', err);
      });
    }

    if (interviewId) {
      try {
        await apiClient.post(`/interviews/${interviewId}/consent`, { consent: true });
        await apiClient.post(`/interviews/${interviewId}/session-token`);
      } catch {
        // Continue with local session fallback
      }
    }

    setTimeout(() => {
      setMessages([
        {
          id: 'ai-init',
          role: 'ai',
          content: `Hello! Welcome to your AI voice interview for the ${role} position at ${company}. Let's begin. ${topics[0].question}`,
          timestamp: new Date().toLocaleTimeString(),
        },
      ]);
      setIsAnalyzing(false);
    }, 1200);
  };

  const submitAnswer = async (text: string) => {
    if (!text.trim() || isAnalyzing) return;

    // eslint-disable-next-line react-hooks/purity
    const currentTimestamp = Date.now();
    const timestamp = new Date(currentTimestamp).toLocaleTimeString();
    setMessages((prev) => [...prev, { id: `c-${currentTimestamp}`, role: 'candidate', content: text, timestamp }]);
    setIsAnalyzing(true);

    // Call FastAPI voice response router if operational, or fallback to local stage logic
    let aiResponseText = '';
    setAiRespondError(null);
    try {
      const res = await fetch(`${siteConfig.aiServiceUrl}/api/v1/ai/interview/respond`, {
        method: 'POST',
        headers: { 'Content-Type': 'application/json' },
        body: JSON.stringify({
          interviewId: interviewId || `intv_${currentTimestamp}`,
          transcript: text,
          turnNumber: messagesRef.current.length + 1,
          stage: phase === 'Introduction' ? 'intro' : phase === 'Core Vetting' ? 'technical' : 'closing',
          jobTitle: role,
          conversationHistory: messages.map(m => ({ speaker: m.role, text: m.content })),
        }),
      });
      if (!res.ok) {
        const errMsg = `AI respond failed: ${res.status} ${res.statusText}`;
        console.error(`[interview] ${errMsg}`);
        setAiRespondError(errMsg);
      } else {
        const data = await res.json();
        if (data && typeof data.text === 'string' && data.text.trim()) {
          aiResponseText = data.text;
        } else {
          console.error('[interview] AI respond returned a malformed response without a text field', data);
          setAiRespondError('AI returned an unexpected response format.');
        }
      }
    } catch (err) {
      const errMsg = err instanceof Error ? err.message : 'Network error contacting AI service.';
      console.error('[interview] AI respond request failed', err);
      setAiRespondError(errMsg);
    }

    setTimeout(() => {
      const currentTopic = topics[topicIndex.current] || topics[0];

      if (!isFollowUp.current) {
        transcriptData.current.push({
          question: currentTopic.question,
          answer: text,
          feedback: '',
        });

        setPhase('Deep-Dive');
        isFollowUp.current = true;
        const responseMsg = aiResponseText || currentTopic.followUp;
        setMessages((prev) => [
          ...prev,
          { id: `ai-${Date.now()}`, role: 'ai', content: responseMsg, timestamp: new Date().toLocaleTimeString() }
        ]);
        setIsAnalyzing(false);
      } else {
        isFollowUp.current = false;
        topicIndex.current += 1;

        if (topicIndex.current < topics.length) {
          setPhase('Core Vetting');
          const nextQ = aiResponseText || `Got it. Moving forward: ${topics[topicIndex.current].question}`;
          setMessages((prev) => [
            ...prev,
            { id: `ai-${Date.now()}`, role: 'ai', content: nextQ, timestamp: new Date().toLocaleTimeString() }
          ]);
          setIsAnalyzing(false);
        } else {
          setPhase('Wrap-up');
          const closingMsg = aiResponseText || `Thank you! That completes our technical evaluation. I will now package your scorecard for the hiring team.`;
          setMessages((prev) => [
            ...prev,
            { id: `ai-${Date.now()}`, role: 'ai', content: closingMsg, timestamp: new Date().toLocaleTimeString() }
          ]);
          setIsAnalyzing(false);
          setTimeout(handleComplete, 2500);
        }
      }
    }, 1500);
  };

  const handleComplete = async () => {
    if (interviewId) {
      try {
        // Send the latest messages via the ref so the saved transcript includes the
        // final candidate answer and closing AI message.
        await apiClient.post(`/interviews/${interviewId}/end`, { transcript: messagesRef.current });
      } catch (err) {
        // The transcript is what the evaluator agent scores server-side, so a
        // failed persist means no real score will be produced. Surface it.
        console.error('[interview] Failed to persist transcript to backend', err);
      }
    }
    // Persists the honest pending state (status: 'pending_evaluation', score: null).
    // A real score is produced server-side by the evaluator agent, never here.
    const results = evaluateInterview({ role, topics, transcriptData: transcriptData.current });
    localStorage.setItem(storageKey, JSON.stringify(results));
    onComplete(results);
  };

  const handleResumeFullscreen = () => {
    if (!document.fullscreenElement) {
      document.documentElement.requestFullscreen().catch((err) => {
        console.error('Failed to enter fullscreen:', err);
      });
    }
    setShowWarningModal(false);
  };

  const handleEliminateCandidate = async () => {
    if (interviewId) {
      try {
        await apiClient.post(`/interviews/${interviewId}/end`, { transcript: messagesRef.current });
      } catch (err) {
        console.error('[interview] Failed to persist transcript to backend on elimination', err);
      }
    }
    const results = {
      status: 'completed' as const,
      isPending: false,
      score: 0,
      feedback: 'Disqualified due to proctoring violations.',
      rubric: { technical: 0, communication: 0, cultureFit: 0 },
      transcript: messagesRef.current.map((item) => ({
        question: item.role === 'ai' ? item.content : '',
        answer: item.role === 'candidate' ? item.content : '',
        feedback: '',
      })),
    };
    localStorage.setItem(storageKey, JSON.stringify(results));
    onComplete(results);
  };

  const simulateSpeaking = () => {
    // No-op: fabricated speech simulation removed. Real candidates respond via live mic.
  };

  return {
    stage,
    phase,
    messages,
    timeRemaining,
    micActive,
    camActive,
    isAnalyzing,
    aiRespondError,
    proctorTelemetry,
    setProctorTelemetry,
    startSession,
    submitAnswer,
    simulateSpeaking,
    wrapUp: handleComplete,
    toggleMic: () => setMicActive(p => !p),
    toggleCam: () => setCamActive(p => !p),
    setStage,
    strikeCount,
    showWarningModal,
    onResumeFullscreen: handleResumeFullscreen,
    onEliminate: handleEliminateCandidate,
  };
}
