import { Job } from './types';

export const mockJobs: Job[] = [
  {
    id: 'job-101',
    orgId: 'org-swiggy',
    orgName: 'Swiggy',
    orgLogo: 'https://logo.clearbit.com/swiggy.com',
    title: 'Senior Frontend Engineer — Consumer Platform',
    description: 'We are looking for a Senior Frontend Engineer to join our core Consumer Web & App team. You will build highly optimized checkout pipelines, improve lazy loading performance of menus, and design micro-frontend modules for millions of food and grocery delivery orders daily.',
    rubric: { technical: 40, communication: 20, problemSolving: 20, experience: 20 },
    thresholds: { minScore: 82, autoOffer: true },
    status: 'active',
    location: 'Bengaluru, KA (Hybrid)',
    salary: '₹28L - ₹42L',
    experienceLevel: 'Senior (5+ years)',
    postedDate: '2026-06-28',
    applicantsCount: 18,
    stages: ['screening', 'assessment', 'voice_screen', 'hr_round', 'decision'],
    assessmentConfig: { mcqCount: 5, codingProblemId: 'virtualized-list', passingScore: 80 }
  },
  {
    id: 'job-102',
    orgId: 'org-razorpay',
    orgName: 'Razorpay',
    orgLogo: 'https://logo.clearbit.com/razorpay.com',
    title: 'Product Manager — Payments Flow',
    description: 'Join the Core Checkout team at Razorpay to build checkout experiences that power over 8 million Indian merchants. You will lead cross-functional engineering groups to design low-latency retry mechanisms and localized UPI payment flows.',
    rubric: { technical: 20, communication: 35, problemSolving: 25, experience: 20 },
    thresholds: { minScore: 85, autoOffer: false },
    status: 'active',
    location: 'Bengaluru, KA (On-site)',
    salary: '₹22L - ₹32L',
    experienceLevel: 'Mid-Senior (4+ years)',
    postedDate: '2026-07-01',
    applicantsCount: 12,
    stages: ['screening', 'assessment', 'voice_screen', 'panel', 'decision'],
    assessmentConfig: { mcqCount: 5, codingProblemId: 'two-sum', passingScore: 75 }
  },
  {
    id: 'job-103',
    orgId: 'org-cred',
    orgName: 'CRED',
    orgLogo: 'https://logo.clearbit.com/cred.club',
    title: 'Full Stack Engineer — Billing & Ledgers',
    description: 'Help us design high-throughput transaction pipelines. You will work across Node, Go, Postgres, and React to build ledger systems that process member bill payments with absolute accuracy and zero double-spend anomalies.',
    rubric: { technical: 45, communication: 15, problemSolving: 20, experience: 20 },
    thresholds: { minScore: 80, autoOffer: false },
    status: 'active',
    location: 'Bengaluru, KA (Hybrid)',
    salary: '₹30L - ₹45L',
    experienceLevel: 'Senior (4+ years)',
    postedDate: '2026-06-15',
    applicantsCount: 24,
    stages: ['screening', 'assessment', 'voice_screen', 'hr_round', 'decision']
  },
  {
    id: 'job-104',
    orgId: 'org-zoho',
    orgName: 'Zoho',
    orgLogo: 'https://logo.clearbit.com/zoho.com',
    title: 'Lead Data Scientist — AI Assistant',
    description: 'Build predictive search algorithms and AI productivity tools inside the Zoho SaaS suite. You will train custom NLP models to automate customer tickets, optimize hybrid database search, and work directly with product leads.',
    rubric: { technical: 50, communication: 10, problemSolving: 25, experience: 15 },
    thresholds: { minScore: 88, autoOffer: false },
    status: 'draft',
    location: 'Chennai, TN (On-site)',
    salary: '₹26L - ₹40L',
    experienceLevel: 'Lead (7+ years)',
    postedDate: '2026-07-02',
    applicantsCount: 0
  },
  {
    id: 'job-105',
    orgId: 'org-zerodha',
    orgName: 'Zerodha',
    orgLogo: 'https://logo.clearbit.com/zerodha.com',
    title: 'Backend Engineer — Core Trading Systems',
    description: 'Work on India\'s largest retail stockbroker. You will design ultra-low latency order routing libraries in Go, manage high-concurrency Redis caching grids, and build resilient socket layers capable of streaming millions of ticks concurrently.',
    rubric: { technical: 50, communication: 10, problemSolving: 25, experience: 15 },
    thresholds: { minScore: 86, autoOffer: false },
    status: 'active',
    location: 'Bengaluru, KA (On-site)',
    salary: '₹24L - ₹38L',
    experienceLevel: 'Mid-Senior (3+ years)',
    postedDate: '2026-06-30',
    applicantsCount: 15
  },
  {
    id: 'job-106',
    orgId: 'org-ola',
    orgName: 'Ola Electric',
    orgLogo: 'https://logo.clearbit.com/olacabs.com',
    title: 'Staff Infrastructure Engineer',
    description: 'Optimize high-throughput telemetry pipelines that capture telemetry from thousands of smart electric scooters. You will build and scale distributed Kubernetes clusters across hybrid clouds, ensuring 99.99% uptime for iot ingestion.',
    rubric: { technical: 45, communication: 15, problemSolving: 20, experience: 20 },
    thresholds: { minScore: 85, autoOffer: false },
    status: 'active',
    location: 'Pune, MH (Hybrid)',
    salary: '₹42L - ₹65L',
    experienceLevel: 'Staff (8+ years)',
    postedDate: '2026-07-02',
    applicantsCount: 8
  },
  {
    id: 'job-107',
    orgId: 'org-meesho',
    orgName: 'Meesho',
    orgLogo: 'https://logo.clearbit.com/meesho.com',
    title: 'Frontend Engineer — Seller Portal',
    description: 'Build responsive interfaces that enable lakhs of micro-entrepreneurs and home sellers across India to manage inventories. Optimize frontend layouts for low-end mobile browsers on slow tier-3 mobile networks.',
    rubric: { technical: 35, communication: 25, problemSolving: 20, experience: 20 },
    thresholds: { minScore: 78, autoOffer: true },
    status: 'active',
    location: 'Bengaluru, KA (Hybrid)',
    salary: '₹14L - ₹22L',
    experienceLevel: 'Mid (2+ years)',
    postedDate: '2026-07-02',
    applicantsCount: 19
  },
  {
    id: 'job-108',
    orgId: 'org-flipkart',
    orgName: 'Flipkart',
    orgLogo: 'https://logo.clearbit.com/flipkart.com',
    title: 'UI Engineer — Search & Recommendations',
    description: 'Design highly interactive product discovery structures for the Flipkart app. Implement smart auto-suggestions, rich filter overlays, and glassmorphic card grids, guaranteeing frame rates of 60fps during major Big Billion Days sale events.',
    rubric: { technical: 40, communication: 20, problemSolving: 20, experience: 20 },
    thresholds: { minScore: 81, autoOffer: false },
    status: 'active',
    location: 'Bengaluru, KA (Remote)',
    salary: '₹18L - ₹28L',
    experienceLevel: 'Senior (4+ years)',
    postedDate: '2026-07-03',
    applicantsCount: 7
  },
  {
    id: 'job-109',
    orgId: 'org-zepto',
    orgName: 'Zepto',
    orgLogo: 'https://logo.clearbit.com/zepto.com',
    title: 'Staff Systems Engineer — 10-Min Dispatch AI',
    description: 'Design real-time dark store inventory allocation engines and driver dispatch optimization models using Rust, Python, and Redis Streams to deliver orders within sub-10 minute SLAs.',
    rubric: { technical: 50, communication: 10, problemSolving: 25, experience: 15 },
    thresholds: { minScore: 88, autoOffer: true },
    status: 'active',
    location: 'Mumbai, MH (On-site)',
    salary: '₹35L - ₹55L',
    experienceLevel: 'Staff (6+ years)',
    postedDate: '2026-07-05',
    applicantsCount: 22
  },
  {
    id: 'job-110',
    orgId: 'org-postman',
    orgName: 'Postman',
    orgLogo: 'https://logo.clearbit.com/postman.com',
    title: 'Senior Developer Advocate — API Platform',
    description: 'Empower millions of API developers worldwide by crafting interactive developer tutorials, open-source Postman collections, and building developer tools.',
    rubric: { technical: 30, communication: 45, problemSolving: 15, experience: 10 },
    thresholds: { minScore: 84, autoOffer: false },
    status: 'active',
    location: 'Bengaluru, KA (Remote)',
    salary: '₹28L - ₹40L',
    experienceLevel: 'Senior (5+ years)',
    postedDate: '2026-07-06',
    applicantsCount: 14
  }
];
