import { Router } from 'express';
import { authRouter } from './auth/auth.routes';
import { candidateProfileRouter } from './candidate/candidate-profile.routes';
import { candidateDashboardRouter } from './candidate/candidate-dashboard.routes';
import { candidateApplicationsRouter } from './candidate/candidate-applications.routes';
import { resumeParserRouter } from './candidate/resume-parser.routes';
import { mockRouter } from './candidate/mock.routes';
import { resumeBuilderRouter } from './candidate/resume-builder.routes';
import { hrDashboardRouter } from './hr/hr-dashboard.routes';
import { hrHoldQueueRouter } from './hr/hr-hold-queue.routes';
import { hrEvaluationsRouter } from './hr/hr-evaluations.routes';
import { analyticsRouter } from './hr/analytics.routes';
import { sentimentRouter } from './hr/sentiment.routes';
import { talentPoolRouter } from './hr/talent-pool.routes';
import { jobRouter } from './jobs/jobs.routes';
import { applicationRouter } from './applications/applications.routes';
import { interviewRouter } from './interviews/interviews.routes';
import { prepRouter } from './prep/prep-content.routes';
import { organizationRouter } from './organization/organization.routes';
import { internalRouter } from './internal/internal.routes';
import { notificationsRouter } from './notifications/notifications.routes';
import { accountRouter } from './account/account.routes';
import { codingRouter } from './coding/coding.routes';
import { proctoringRouter } from './proctoring/proctoring.routes';

export const apiRouter = Router();

// Domain-driven API v1 Route Mounts
apiRouter.use('/auth', authRouter);
apiRouter.use('/organizations', organizationRouter);
apiRouter.use('/jobs', jobRouter);
apiRouter.use('/applications', applicationRouter);
apiRouter.use('/coding', codingRouter);
apiRouter.use('/candidate', candidateProfileRouter);
apiRouter.use('/candidate', candidateDashboardRouter);
apiRouter.use('/candidate', candidateApplicationsRouter);
apiRouter.use('/candidate', resumeParserRouter);
apiRouter.use('/proctoring', proctoringRouter);

apiRouter.use('/hr/analytics', analyticsRouter);
apiRouter.use('/hr/sentiment', sentimentRouter);
apiRouter.use('/hr/talent-pool', talentPoolRouter);
apiRouter.use('/hr', hrDashboardRouter);
apiRouter.use('/hr', hrHoldQueueRouter);
apiRouter.use('/hr', hrEvaluationsRouter);
apiRouter.use('/notifications', notificationsRouter);
apiRouter.use('/interviews', interviewRouter);
apiRouter.use('/mock', mockRouter);
apiRouter.use('/resume-builder', resumeBuilderRouter);
apiRouter.use('/prep', prepRouter);
apiRouter.use('/internal', internalRouter);
apiRouter.use('/', accountRouter);