import logging
import httpx
from core.config import settings
from core.http_client import callback_client
from services.embedding_service import embed_text, cosine_similarity

logger = logging.getLogger("sourcing_worker")


# ML_BYPASS: external sourcing — integrate LinkedIn Recruiter API or scraping pipeline when ready
async def process_sourcing_job(job_data: dict) -> bool:
    """
    Process auto-sourcing & vector indexing job for published job openings.
    1. Fetch job description from Express API.
    2. Generate job description embedding (768-dim vector).
    3. Save pre-ranked recommended candidate pool.
    4. Report back to Express API via internal callback.
    """
    job_id = job_data.get("jobId")
    if not job_id:
        logger.error("Missing jobId in sourcing job payload.")
        return False

    logger.info(f"Processing sourcing index job for jobId: {job_id}")

    try:
        # Fetch raw job info
        async with httpx.AsyncClient() as client:
            resp = await client.get(
                f"{settings.express_api_base_url}/internal/jobs/{job_id}/raw",
                headers={"X-Internal-Service-Secret": settings.internal_service_secret},
            )
            resp.raise_for_request()
            job_info = resp.json().get("data", {})

        job_desc = job_info.get("description", "")
        org_id = job_info.get("org_id")

        # Generate 768-dim vector embedding for job
        job_vector = embed_text(job_desc)

        # Mock sample recommendations generated by sourcing agent
        recommended_candidates = [
            {
                "name": "Candidate Alpha",
                "match_score": 92.5,
                "skills": ["TypeScript", "React", "Node.js"],
                "sourced_from": "NextRound Talent Network",
            },
            {
                "name": "Candidate Beta",
                "match_score": 88.0,
                "skills": ["Python", "FastAPI", "PostgreSQL"],
                "sourced_from": "NextRound Talent Network",
            },
        ]

        # Callback candidates back to Express
        await callback_client.post_callback(
            f"internal/sourcing/{job_id}/candidates",
            {"candidates": recommended_candidates}
        )

        # Log agent execution
        log_payload = {
            "job_id": job_id,
            "org_id": org_id,
            "agent_name": "sourcing_agent",
            "action": "sourcing_index",
            "input": {"job_id": job_id},
            "output": {"candidates_count": len(recommended_candidates)},
            "status": "completed",
        }
        await callback_client.post_callback("internal/agent-logs", log_payload)

        logger.info(f"Successfully completed sourcing index job for jobId: {job_id}")
        return True

    except Exception as e:
        logger.error(f"Failed to process sourcing job for jobId {job_id}: {e}")
        return False
